// <auto-generated />
using ChargingStations.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ChargingStations.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("ChargingStations.Domain.ChargerAggregate.Charger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ChargerModelId")
                        .HasColumnType("integer")
                        .HasColumnName("charger_model_id");

                    b.Property<double>("ChargingFeePerKwh")
                        .HasColumnType("double precision")
                        .HasColumnName("charging_fee_per_kwh");

                    b.Property<int>("ChargingStationId")
                        .HasColumnType("integer")
                        .HasColumnName("charging_station_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("ChargerModelId");

                    b.HasIndex("ChargingStationId");

                    b.ToTable("charger");
                });

            modelBuilder.Entity("ChargingStations.Domain.ChargerModelAggregate.ChargerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("charger_model");
                });

            modelBuilder.Entity("ChargingStations.Domain.ChargingStationAggregate.ChargingStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("charging_station");
                });

            modelBuilder.Entity("ChargingStations.Domain.TenantAggregate.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("tenant");
                });

            modelBuilder.Entity("ChargingStations.Domain.ChargerAggregate.Charger", b =>
                {
                    b.HasOne("ChargingStations.Domain.ChargerModelAggregate.ChargerModel", "ChargerModel")
                        .WithMany("Chargers")
                        .HasForeignKey("ChargerModelId")
                        .HasConstraintName("FK_Charger_ChargerModel_ChargerModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChargingStations.Domain.ChargingStationAggregate.ChargingStation", "ChargingStation")
                        .WithMany("Chargers")
                        .HasForeignKey("ChargingStationId")
                        .HasConstraintName("FK_Charger_ChargingStation_ChargingStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChargerModel");

                    b.Navigation("ChargingStation");
                });

            modelBuilder.Entity("ChargingStations.Domain.ChargingStationAggregate.ChargingStation", b =>
                {
                    b.HasOne("ChargingStations.Domain.TenantAggregate.Tenant", "Tenant")
                        .WithMany("ChargingStations")
                        .HasForeignKey("TenantId")
                        .HasConstraintName("FK_ChargingStation_Tenant_TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ChargingStations.Domain.ChargerModelAggregate.ChargerModel", b =>
                {
                    b.Navigation("Chargers");
                });

            modelBuilder.Entity("ChargingStations.Domain.ChargingStationAggregate.ChargingStation", b =>
                {
                    b.Navigation("Chargers");
                });

            modelBuilder.Entity("ChargingStations.Domain.TenantAggregate.Tenant", b =>
                {
                    b.Navigation("ChargingStations");
                });
#pragma warning restore 612, 618
        }
    }
}
